default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: text_to_speech_application

test:
  <<: *default
  database: text_to_speech_application_test

production:
  <<: *default
  database: text_to_speech_application_production
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
